# Copyright (C) 2023 Bankdata (bankdata@bankdata.dk)

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

builds:
  - main: cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude: []

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

dockers:
- image_templates:
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-amd64"
  use: buildx
  goarch: amd64
  dockerfile: build/package/Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-arm64"
  use: buildx
  goarch: arm64
  dockerfile: build/package/Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64"

docker_manifests:
- name_template: "ghcr.io/bankdata/styra-controller:latest"
  image_templates:
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-amd64"
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-arm64"
- name_template: "ghcr.io/bankdata/styra-controller:{{ .Major }}"
  image_templates:
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-amd64"
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-arm64"
- name_template: "ghcr.io/bankdata/styra-controller:{{ .Major }}.{{ .Minor }}"
  image_templates:
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-amd64"
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-arm64"
- name_template: "ghcr.io/bankdata/styra-controller:{{ .Version }}"
  image_templates:
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-amd64"
  - "ghcr.io/bankdata/styra-controller:{{ .Version }}-arm64"

release:
  github:
    owner: Bankdata
    name: styra-controller
  footer: |
    ## Docker Images
    - `ghcr.io/bankdata/styra-controller:latest`
    - "ghcr.io/bankdata/styra-controller:{{ .Version }}"
    - "ghcr.io/bankdata/styra-controller:{{ .Version }}-amd64"
    - "ghcr.io/bankdata/styra-controller:{{ .Version }}-arm64"
