dir: "{{ .InterfaceDir }}/mocks"
filename: "{{ .InterfaceNameSnake }}.go"
outpkg: "mocks"
mockname: "{{ .InterfaceName }}"
with-expecter: false
disable-version-string: true
packages:
  github.com/bankdata/styra-controller/pkg/styra:
    config:
      all: true
  github.com/bankdata/styra-controller/internal/webhook:
    config:
      all: true
