# permissions for end users to view projectconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: projectconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: styra-controller
    app.kubernetes.io/part-of: styra-controller
    app.kubernetes.io/managed-by: kustomize
  name: projectconfig-viewer-role
rules:
- apiGroups:
  - config.bankdata.dk
  resources:
  - projectconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.bankdata.dk
  resources:
  - projectconfigs/status
  verbs:
  - get
