---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - statefulset
  verbs:
  - get
  - patch
- apiGroups:
  - styra.bankdata.dk
  resources:
  - libraries
  - systems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - styra.bankdata.dk
  resources:
  - libraries/finalizers
  - systems/finalizers
  verbs:
  - update
- apiGroups:
  - styra.bankdata.dk
  resources:
  - libraries/status
  - systems/status
  verbs:
  - get
  - patch
  - update
