# permissions for end users to view systems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: system-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: styra-controller
    app.kubernetes.io/part-of: styra-controller
    app.kubernetes.io/managed-by: kustomize
  name: system-viewer-role
rules:
- apiGroups:
  - styra.bankdata.dk
  resources:
  - systems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - styra.bankdata.dk
  resources:
  - systems/status
  verbs:
  - get
