//go:build !ignore_autogenerated

/*
Copyright (C) 2023 Bankdata (bankdata@bankdata.dk)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitCredential) DeepCopyInto(out *GitCredential) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitCredential.
func (in *GitCredential) DeepCopy() *GitCredential {
	if in == nil {
		return nil
	}
	out := new(GitCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationWebhookConfig) DeepCopyInto(out *NotificationWebhookConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationWebhookConfig.
func (in *NotificationWebhookConfig) DeepCopy() *NotificationWebhookConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationWebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectConfig) DeepCopyInto(out *ProjectConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ControllerManagerConfigurationSpec.DeepCopyInto(&out.ControllerManagerConfigurationSpec)
	if in.GitCredentials != nil {
		in, out := &in.GitCredentials, &out.GitCredentials
		*out = make([]*GitCredential, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(GitCredential)
				**out = **in
			}
		}
	}
	if in.NotificationWebhook != nil {
		in, out := &in.NotificationWebhook, &out.NotificationWebhook
		*out = new(NotificationWebhookConfig)
		**out = **in
	}
	if in.Sentry != nil {
		in, out := &in.Sentry, &out.Sentry
		*out = new(SentryConfig)
		**out = **in
	}
	if in.SSO != nil {
		in, out := &in.SSO, &out.SSO
		*out = new(SSOConfig)
		**out = **in
	}
	out.Styra = in.Styra
	if in.SystemUserRoles != nil {
		in, out := &in.SystemUserRoles, &out.SystemUserRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectConfig.
func (in *ProjectConfig) DeepCopy() *ProjectConfig {
	if in == nil {
		return nil
	}
	out := new(ProjectConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSOConfig) DeepCopyInto(out *SSOConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSOConfig.
func (in *SSOConfig) DeepCopy() *SSOConfig {
	if in == nil {
		return nil
	}
	out := new(SSOConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SentryConfig) DeepCopyInto(out *SentryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SentryConfig.
func (in *SentryConfig) DeepCopy() *SentryConfig {
	if in == nil {
		return nil
	}
	out := new(SentryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StyraConfig) DeepCopyInto(out *StyraConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StyraConfig.
func (in *StyraConfig) DeepCopy() *StyraConfig {
	if in == nil {
		return nil
	}
	out := new(StyraConfig)
	in.DeepCopyInto(out)
	return out
}
