apiVersion: config.bankdata.dk/v2alpha2
kind: ProjectConfig

# controllerClass sets a controller class for this controller. This allows the
# provided CRDs to target a specific controller. This is useful when running
# multiple controllers in the same cluster.
controllerClass: ""

# deletionProtectionDefault sets the default to use with regards to deletion
# protection if it is not set on the resource.
deletionProtectionDefault: false

# disableCRDWebhooks disables the CRD webhooks on the controller. If running
# multiple controllers in the same cluster, only one will need to have it's
# webhooks enabled.
disableCRDWebhooks: false

# enableMigrations enables the system migration annotation. This should be kept
# disabled unless migrations need to be done.
enableMigrations: false

# gitCredentials holds a list of git credential configurations. The repoPrefix
# of the git credential will be matched angainst repository URL in order to
# determine which credential to use. The git credential with the longest
# matching repoPrefix will be selected.
gitCredentials: []
# - user: my-git-user
#   password: my-git-password
#   repoPrefix: https://github.com/my-org

# leaderElection contains configuration for the controller-runtime leader
# election.
#leaderElection:
#  leaseDuration: 15s
#  renewDeadLine: 10s
#  retryPeriod: 2s

# logLevel sets the logging level of the controller. A higher number gives more
# verbosity. A number higher than 0 should only be used for debugging purposes.
logLevel: 0

# notificationWebhook contains configuration for how to call the notification
# webhook.
#notificationWebhook:
#  address: ""

# sentry contains configuration for how errors should be reported to sentry.
#sentry:
#  debug: false
#  dsn: ""
#  environment: ""
#  httpsProxy: ""

# sso contains configuration for how to use SSO tokens for determining what
# groups a user belongs to. This can be used to grant members of a certain
# group access to systems.
#sso:
#  identityProvider: ""
#  jwtGroupsClaim: ""

# styra contains configuration for connecting to the Styra DAS apis
styra:
  address: ""
  token: ""

# systemPrefix is a prefix for all the systems that the controller creates
# in Styra DAS. This is useful in order to be able to identify what
# controller created a system in a shared Styra DAS instance.
systemPrefix: ""

# systemSuffix is a suffix for all the systems that the controller creates
# in Styra DAS. This is useful in order to be able to identify what
# controller created a system in a shared Styra DAS instance.
systemSuffix: ""

# systemUserRoles is a list of Styra DAS system level roles which the subjects of
# a system will be granted.
systemUserRoles: []
# - SystemViewer
# - SystemInstall
