//go:build !ignore_autogenerated

/*
Copyright (C) 2025 Bankdata (bankdata@bankdata.dk)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha2

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleObjectStorage) DeepCopyInto(out *BundleObjectStorage) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3ObjectStorage)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleObjectStorage.
func (in *BundleObjectStorage) DeepCopy() *BundleObjectStorage {
	if in == nil {
		return nil
	}
	out := new(BundleObjectStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionAPIConfig) DeepCopyInto(out *DecisionAPIConfig) {
	*out = *in
	out.Reporting = in.Reporting
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionAPIConfig.
func (in *DecisionAPIConfig) DeepCopy() *DecisionAPIConfig {
	if in == nil {
		return nil
	}
	out := new(DecisionAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionLog) DeepCopyInto(out *DecisionLog) {
	*out = *in
	in.RequestContext.DeepCopyInto(&out.RequestContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionLog.
func (in *DecisionLog) DeepCopy() *DecisionLog {
	if in == nil {
		return nil
	}
	out := new(DecisionLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionLogReporting) DeepCopyInto(out *DecisionLogReporting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionLogReporting.
func (in *DecisionLogReporting) DeepCopy() *DecisionLogReporting {
	if in == nil {
		return nil
	}
	out := new(DecisionLogReporting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitCredentials) DeepCopyInto(out *GitCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitCredentials.
func (in *GitCredentials) DeepCopy() *GitCredentials {
	if in == nil {
		return nil
	}
	out := new(GitCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTP) DeepCopyInto(out *HTTP) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTP.
func (in *HTTP) DeepCopy() *HTTP {
	if in == nil {
		return nil
	}
	out := new(HTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPMetricsConfig) DeepCopyInto(out *HTTPMetricsConfig) {
	*out = *in
	if in.Buckets != nil {
		in, out := &in.Buckets, &out.Buckets
		*out = make([]float64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPMetricsConfig.
func (in *HTTPMetricsConfig) DeepCopy() *HTTPMetricsConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPMetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderElectionConfig) DeepCopyInto(out *LeaderElectionConfig) {
	*out = *in
	out.LeaseDuration = in.LeaseDuration
	out.RenewDeadline = in.RenewDeadline
	out.RetryPeriod = in.RetryPeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionConfig.
func (in *LeaderElectionConfig) DeepCopy() *LeaderElectionConfig {
	if in == nil {
		return nil
	}
	out := new(LeaderElectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfig) DeepCopyInto(out *MetricsConfig) {
	*out = *in
	in.Prometheus.DeepCopyInto(&out.Prometheus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfig.
func (in *MetricsConfig) DeepCopy() *MetricsConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSelector) DeepCopyInto(out *NamespaceSelector) {
	*out = *in
	if in.MatchPatterns != nil {
		in, out := &in.MatchPatterns, &out.MatchPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSelector.
func (in *NamespaceSelector) DeepCopy() *NamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPABundleServer) DeepCopyInto(out *OPABundleServer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPABundleServer.
func (in *OPABundleServer) DeepCopy() *OPABundleServer {
	if in == nil {
		return nil
	}
	out := new(OPABundleServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPAConfig) DeepCopyInto(out *OPAConfig) {
	*out = *in
	in.DecisionLogs.DeepCopyInto(&out.DecisionLogs)
	in.Metrics.DeepCopyInto(&out.Metrics)
	if in.BundleServer != nil {
		in, out := &in.BundleServer, &out.BundleServer
		*out = new(OPABundleServer)
		**out = **in
	}
	if in.DecisionAPIConfig != nil {
		in, out := &in.DecisionAPIConfig, &out.DecisionAPIConfig
		*out = new(DecisionAPIConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPAConfig.
func (in *OPAConfig) DeepCopy() *OPAConfig {
	if in == nil {
		return nil
	}
	out := new(OPAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPAConfigSpec) DeepCopyInto(out *OPAConfigSpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Bundle != nil {
		in, out := &in.Bundle, &out.Bundle
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Bundles != nil {
		in, out := &in.Bundles, &out.Bundles
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.DecisionLogs != nil {
		in, out := &in.DecisionLogs, &out.DecisionLogs
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			var outVal *runtime.RawExtension
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(runtime.RawExtension)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultDecision != nil {
		in, out := &in.DefaultDecision, &out.DefaultDecision
		*out = new(string)
		**out = **in
	}
	if in.DefaultAuthorizationDecision != nil {
		in, out := &in.DefaultAuthorizationDecision, &out.DefaultAuthorizationDecision
		*out = new(string)
		**out = **in
	}
	if in.Caching != nil {
		in, out := &in.Caching, &out.Caching
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.PersistenceDirectory != nil {
		in, out := &in.PersistenceDirectory, &out.PersistenceDirectory
		*out = new(string)
		**out = **in
	}
	if in.DistributedTracing != nil {
		in, out := &in.DistributedTracing, &out.DistributedTracing
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricsExport != nil {
		in, out := &in.MetricsExport, &out.MetricsExport
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(OPAServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(OPAStorageConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPAConfigSpec.
func (in *OPAConfigSpec) DeepCopy() *OPAConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OPAConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPAControlPlaneConfig) DeepCopyInto(out *OPAControlPlaneConfig) {
	*out = *in
	if in.GitCredentials != nil {
		in, out := &in.GitCredentials, &out.GitCredentials
		*out = make([]*GitCredentials, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(GitCredentials)
				**out = **in
			}
		}
	}
	if in.BundleObjectStorage != nil {
		in, out := &in.BundleObjectStorage, &out.BundleObjectStorage
		*out = new(BundleObjectStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultRequirements != nil {
		in, out := &in.DefaultRequirements, &out.DefaultRequirements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPAControlPlaneConfig.
func (in *OPAControlPlaneConfig) DeepCopy() *OPAControlPlaneConfig {
	if in == nil {
		return nil
	}
	out := new(OPAControlPlaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPAServerConfig) DeepCopyInto(out *OPAServerConfig) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Decoding != nil {
		in, out := &in.Decoding, &out.Decoding
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.LoggerPlugin != nil {
		in, out := &in.LoggerPlugin, &out.LoggerPlugin
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPAServerConfig.
func (in *OPAServerConfig) DeepCopy() *OPAServerConfig {
	if in == nil {
		return nil
	}
	out := new(OPAServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPAStorageConfig) DeepCopyInto(out *OPAStorageConfig) {
	*out = *in
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPAStorageConfig.
func (in *OPAStorageConfig) DeepCopy() *OPAStorageConfig {
	if in == nil {
		return nil
	}
	out := new(OPAStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectConfig) DeepCopyInto(out *ProjectConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(NamespaceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LeaderElection != nil {
		in, out := &in.LeaderElection, &out.LeaderElection
		*out = new(LeaderElectionConfig)
		**out = **in
	}
	in.OPA.DeepCopyInto(&out.OPA)
	if in.OPAConfig != nil {
		in, out := &in.OPAConfig, &out.OPAConfig
		*out = new(OPAConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OPAControlPlaneConfig != nil {
		in, out := &in.OPAControlPlaneConfig, &out.OPAControlPlaneConfig
		*out = new(OPAControlPlaneConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectConfig.
func (in *ProjectConfig) DeepCopy() *ProjectConfig {
	if in == nil {
		return nil
	}
	out := new(ProjectConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusMetricsConfig) DeepCopyInto(out *PrometheusMetricsConfig) {
	*out = *in
	in.HTTP.DeepCopyInto(&out.HTTP)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusMetricsConfig.
func (in *PrometheusMetricsConfig) DeepCopy() *PrometheusMetricsConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusMetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestContext) DeepCopyInto(out *RequestContext) {
	*out = *in
	in.HTTP.DeepCopyInto(&out.HTTP)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestContext.
func (in *RequestContext) DeepCopy() *RequestContext {
	if in == nil {
		return nil
	}
	out := new(RequestContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ObjectStorage) DeepCopyInto(out *S3ObjectStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ObjectStorage.
func (in *S3ObjectStorage) DeepCopy() *S3ObjectStorage {
	if in == nil {
		return nil
	}
	out := new(S3ObjectStorage)
	in.DeepCopyInto(out)
	return out
}
